### PR TITLE
make URL configurable

### PR DESCRIPTION
**Pull request by spion06**

### CODE REVIEW

**Comment by spion06** [comment]
I wasn't able to add chefspec tests for some of the older platforms as [fauxhai](https://github.com/customink/fauxhai) doesn't seem to support them

**Comment by spion06** [comment]
@jtimberman any update on this PR? Just wanting see if there something else you want to see done here

**Comment by cullenmcdermott** [comment]
+1

**Comment by spion06** [comment]
bump

**Comment by jtimberman** [comment]
I'm a terrible maintainer. I don't have time to look at this. I added a couple people who might, but I know they're swamped too.

**Comment by jtimberman** [comment]
@tas50 @iennae Do you have cycles to look into this? If not, I'm open to adding someone else to maintain this cookbook.

**Pull request merged**
